[project]
name = "JanusReader"
version = "0.18.1"
description="Python Reader for the data from JANUS instrument suite on-board the ESA mission JUICE"
requires-python = ">=3.14,<4"
dependencies = [
    "rich-click (>=1.9.7,<2.0.0)",
    "numpy (>=2.4.2,<3.0.0)",
    "semantic-version-tools (>=1.4.1,<2.0.0)",
    "myxmltools (>=0.2.0,<0.3.0)",


]

authors = [{name="Romolo Politi", email ="Romolo.Politi@inaf.it" },
    {name="Luca Penasa", email = "Luca.Penasa@inaf.it"}
]
license = "GPL-3.0-only"

maintainers= [{name="Romolo Politi", email ="Romolo.Politi@inaf.it" },
    {name="Luca Penasa", email = "Luca.Penasa@inaf.it"}
]
keywords = [
    "ESA",
    "Space Missions",
    "JUICE",
    "JANUS",
    "Jupiter"
]

readme = "README.md"

classifiers = [
    "Natural Language :: English",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.14"
]

[project.urls]
Repository = "https://github.com/JANUS-JUICE/janusReader"

[project.scripts]
janusReader = "JanusReader.cli:action"

[project.optional-dependencies]
docs = ["sphinx"]

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
default-groups = ["devel", "test"]

[tool.uv.build-backend]
module-name = "JanusReader"
source-include = ["tests/**", "CHNGELOG.md", "CITATION.cff"]
source-exclude = ["src/JanusReader/phases.py", "src/JanusReader/tools.py"]
wheel-exclude = ["src/JanusReader/phases.py", "src/JanusReader/tools.py"]

[dependency-groups]
devel = [
    "ruff (>=0.15.2,<0.16.0)"
]
test = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "coverage (>=7.13.4,<8.0.0)",
    "coverage-lcov (>=0.3.0,<0.4.0)",
    "pytest-rich (>=0.2.0,<0.3.0)",
    "pyright (>=1.1.408,<2.0.0)",
    "pytest-xdist (>=3.8.0,<4.0.0)"
]

[tool.pytest]
minversion = "9.0"
addopts = [
    "--basetemp=/tmp/pytest",
    "--verbosity=3", 
    "--tb=line", 
    "--capture=sys", 
    "--show-capture=all",
    "--cov=JanusReader",
    "--cov-report=term",
    "--cov-report=html:coverage/coverage_html",
    "--cov-report=xml:coverage/coverage.xml", 
    "--cov-report=json:coverage/coverage.json"
]
testpaths=[
    "tests"
]

[tool.coverage.run]
branch=true
omit=["tests/*","run.py"]
