name: "Pull Request Docs Check"
on: 
- pull_request
- push
- workflow_dispach

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
      
