name: "Pull Request Docs Check"
on: 
- pull_request
- push
- workflow_dispatch

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - run: pip install furo
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html docs/source docs/_build"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/
      
